---
- name: Configure the system image
  hosts: localhost
  become: yes
  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        force: yes

    - name: Add the Google Cloud Ops Agent GPG key
      ansible.builtin.apt_key:
        url: "https://packages.cloud.google.com/apt/google-cloud-ops-agent-archive-keyring.gpg"
        state: present

    - name: Add Google Cloud Ops Agent repository
      ansible.builtin.shell: |
        echo "deb [signed-by=/usr/share/keyrings/google-cloud-ops-agent-archive-keyring.gpg] https://packages.cloud.google.com/apt google-cloud-ops-agent stable main" | sudo tee /etc/apt/sources.list.d/google-cloud-ops-agent.list

    - name: Update apt cache after adding the repository
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Google Cloud Ops Agent
      ansible.builtin.apt:
        name: google-cloud-ops-agent
        state: present

    - name: Install the application binary
      ansible.builtin.copy:
        src: ~/app-binary
        dest: /usr/local/bin/app-binary
        mode: '0755'

    - name: Create systemd service for the application
      ansible.builtin.copy:
        dest: /etc/systemd/system/app-binary.service
        content: |
          [Unit]
          Description=Go application
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/app-binary
          Restart=always
          User=root
          Group=root
          Environment=PATH=/usr/local/bin:$PATH
          WorkingDirectory=/root

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start the service
      ansible.builtin.systemd:
        name: app-binary.service
        enabled: yes
        state: started
